openapi: 3.0.3
info:
  title: Goods Vehicle Movements Port
  contact: {}
  version: '1.0'
servers:
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk
    description: Production
paths:
  /customs/goods-movement-system-port/{portId}/arrivals/controlled:
    $ref: './get-controlled-arrivals.yaml'
  /customs/goods-movement-system-port/{portId}/departures/controlled:
    $ref: './get-controlled-departures.yaml'
  /customs/goods-movement-system-port/{portId}/departures:
    $ref: './get-checked-in.yaml'
  /customs/goods-movement-system-port/reference-data:
    $ref: './get-reference-data.yaml'

components:
  securitySchemes:
    applicationRestricted:
      $ref: './common/schemas/security-components.yaml#/applicationRestricted'